web/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from . import views

web/app/main/views.py
import datetime
import logging
import os

from flask import abort, current_app, escape, redirect, render_template, request, session, url_for
from jinja2 import TemplateNotFound
from . import main


@main.route('/home/')
def main_home():
    return redirect(url_for('.main_page'))


@main.route('/', defaults={'page': 'index'})
@main.route('/<page>/')
def main_page(page):
    try:
        logging.debug( 'main_page( page:%s )' % (page) )
        return render_template('%s.html' % (page))
    except TemplateNotFound:
        logging.info('TemplateNotFound: %s.html' % (page))
        abort(404)


@main.route('/info/')
def main_info():
    result = ''
    result += '<br/><a href="'+url_for('.info_date')+'">show datetime</a>'
    result += '<br/><a href="'+url_for('.info_config')+'">show app.config</a>'
    result += '<br/><a href="'+url_for('.info_url_map')+'">show url_map</a>'
    result += '<br/><a href="'+url_for('.info_request')+'">show request</a>'
    result += '<br/><a href="'+url_for('.info_session')+'">show session</a>'
    result += '<br/><a href="'+url_for('.info_session_clear')+'">clear session</a>'
    return result


@main.route('/info/date')
def info_date():
    ts = datetime.datetime.now().strftime("%Y/%m/%d @ %H:%M:%S")
    return "Current Datetime :<pre> %s </pre>" % ts


@main.route('/info/config')
def info_config():
    cnf = dict(current_app.config)
    return "'%s' Config :<pre> %s </pre>" % (os.getenv('FLASK_CONFIG'),cnf)


@main.route('/info/url_map')
def info_url_map():
    return "current_app.url_map :<pre> %s </pre>" % escape(current_app.url_map)


@main.route('/info/request')
def info_request():
    result = '<b>REQUEST</b>'
    result += "<br/><b>request.method</b> : %s" % request.method
    result += "<br/><b>request.args</b>"
    for key in sorted(request.args.keys()):
        result += "<br/>[%s] : %s" % (key,request.args[key])
    result += "<br/><b>request.form</b>"
    for key in sorted(request.form.keys()):
        result += "<br/>[%s] : %s" % (key,request.form[key])
    result += "<br/><b>request.files</b>"
    for key in sorted(request.files.keys()):
        result += "<br/>[%s] : %s" % (key,request.files[key])
    result += "<br/><b>request.cookies</b>"
    for key in sorted(request.cookies.keys()):
        result += "<br/>[%s] : %s" % (key,request.cookies[key])
    result += "<br/><b>request.environ</b>"
    for key in sorted(request.environ.keys()):
        result += "<br/>[%s] : %s" % (key,request.environ[key])
    return result


@main.route('/info/session')
def info_session():
    result = ''
    for key in session.keys():
        result += "<br/>"+key+" : "+str(session[key])
    return "Session : "+result


@main.route('/info/session_clear')
def info_session_clear():
    session.clear()
    return redirect(url_for('.info_session'))

web/app/main/templates/admin.html
{% extends "base.html" %}


<!-- BLOCK: title -->
{% block title %}{{super()}} - Admin{% endblock %}


<!-- BLOCK: breadcrumb -->
{% block breadcrumb %}
{{super()}}
<li><a href="/admin/">Admin</a></li>
{% endblock %}


<!-- BLOCK: content -->
{% block content %}

<p>This is the landing page for the admin section.</p>

<ol>
<li><a href="{{ url_for('item.item_list') }}">Items</a></li>
<li><a href="{{ url_for('user.user_list') }}">Users</a></li>
</ol>


{% endblock content %}


<!-- BLOCK: templates -->
{% block templates %}{{super()}} - admin.html{% endblock %}

{# end web/app/main/templates/admin.html #}

web/app/main/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}

<!-- BLOCK: html_attribs -->
{% block html_attribs %}{{super()}} lang="en"{% endblock %}

<!-- BLOCK: metas -->
{% block metas %}{{super()}}{% endblock %}

<!-- BLOCK: styles -->
{% block styles %}
    {% block scripts %}{{super()}}
        <script src="{{url_for('static', filename='js/flaskapp.js')}}"></script>
    {% endblock %}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='css/flaskapp.css')}}">
{% endblock %}

<!-- BLOCK: body_attribs -->
{% block body_attribs %}{{super()}}{% endblock %}

<!-- BLOCK: title -->
{% block title %}{{super()}}FlaskApp{% endblock %}

<!-- BLOCK: body, navbar, header, main, footer, scripts -->
{% block body %}

    {% block navbar %}{% include 'navbar_main.html' %}{% endblock %}
    {% block header %}
    <div id="header" class="container-fluid">
        <div class="row">
            <div id="header_left" class="col-md-4">
                {% block header_left %}
<a href="{{ url_for('main.main_home') }}">
<img id="site_logo" src="/static/media/pdxcodeguild.png" width="80" />
</a>
<span id="site_title">FlaskApp</span>
                {% endblock %}
            </div>
            <div id="header_center" class="col-md-4 text-center">
                {% block header_center %}{% endblock %}
            </div>
            <div id="header_right" class="col-md-4 text-right">
                {% block header_right %}{% endblock %}
                {% if current_user.user_email %}
                    <a href="{{ url_for('user.user_profile') }}">{{ current_user.user_email }}</a>
                {% else %}
                    <a href="{{ url_for('user.user_login') }}">Login</a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div id="breadcrumb" class="col-md-12">
                <ol class="breadcrumb">
                {% block breadcrumb %}<li><a href="{{ url_for('main.main_home') }}">Home</a></li>{% endblock %}
                </ol>
            </div>
        </div>
    </div>
    <hr id="header_hr" size="1"/>
    {% endblock %}

    <div id="messages" class="container-fluid flashed-messages">
        <div class="row">
            <div class="col-md-12">
                {{ utils.flashed_messages(container=False, dismissible=True) }}
            </div>
        </div>
    </div>

    {% block main %}
    <div id="main" class="container-fluid layout-1col">
        <div class="row">
            <div id="content" class="col-md-12">
                {% block content %}block content{% endblock %}
            </div>
        </div>
    </div>
    {% endblock %}

    {% block footer %}
    <hr id="footer_hr" size="1"/>
    <div id="footer" class="container-fluid">
        <div class="row">
            <div id="footer_left" class="col-md-4">
                <p>{% block footer_left %}{% endblock %}</p>
            </div>
            <div id="footer_center" class="col-md-4 text-center">
                <p>{% block footer_center %}<b>&lt;PDXCodeGuild /&gt;</b>{% endblock %}</p>
            </div>
            <div id="footer_right" class="col-md-4 text-right">
                <p>{% block footer_right %}{% endblock %}</p>
            </div>
        </div>
    </div>
    {% endblock %}

    {% if config['DEBUG'] %}
<div id="debuginfo"><pre>
DEBUG:
{% if current_user.user_email %}<b>LOGGED IN:</b> {{ current_user.user_email }}{% else %}<b>LOGGED OUT</b>{% endif %}
<b>TEMPLATES:</b> {% block templates %}base.html{% endblock %}
<b>REQUEST.ARGS:</b> {{ request.args }}
<b>REQUEST.COOKIES:</b> {{ request.cookies }}
<b>SESSION:</b> {{ session }}
<b>QUERIES :</b> {{ debug_queries() }}
<b>DATETIME :</b> {{ current_datetime() }}
</pre></div>
    {% endif %}

{% endblock %}


{# end web/app/main/templates/base.html #}

web/app/main/templates/index.html
{% extends "base.html" %}


<!-- BLOCK: title -->
{% block title %}{{super()}} - Home{% endblock %}


<!-- BLOCK: content -->
{% block content %}

<p>This is the Homepage.</p>

{% endblock %}


<!-- BLOCK: templates -->
{% block templates %}{{super()}} - index.html{% endblock %}

{# end web/app/main/templates/index.html #}

web/app/main/templates/layout_1col.html
{% extends "base.html" %}

<!-- BLOCK: main : content -->
{% block main %}
<div id="main" class="container-fluid layout-1col">
    <div class="row">
        <div id="content" class="col-md-12">
            {% block content %}block content{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

<!-- BLOCK: templates -->
{% block templates %}{{super()}} - layout_1col.html{% endblock %}

{# end web/app/main/templates/layout_1col.html #}

web/app/main/templates/layout_2col.html
{% extends "base.html" %}

<!-- BLOCK: main : content_left, content -->
{% block main %}
<div id="main" class="container-fluid layout-2col">
    <div class="row">
        <div id="content_left" class="col-md-3">
            {% block content_left %}block content_left{% endblock %}
        </div>
        <div id="content" class="col-md-9">
            {% block content %}block content{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

<!-- BLOCK: templates -->
{% block templates %}{{super()}} - layout_2col.html{% endblock %}

{# end web/app/main/templates/layout_2col.html #}

web/app/main/templates/layout_3col.html
{% extends "base.html" %}

<!-- BLOCK: main : content_left, content, content_right -->
{% block main %}
<div id="main" class="container-fluid layout-3col">
    <div class="row">
        <div id="content_left" class="col-md-2">
            {% block content_left %}block content_left{% endblock %}
        </div>
        <div id="content" class="col-md-8">
            {% block content %}block content{% endblock %}
        </div>
        <div id="content_right" class="col-md-2">
            {% block content_right %}block content_right{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

<!-- BLOCK: templates -->
{% block templates %}{{super()}} - layout_3col.html{% endblock %}

{# end web/app/main/templates/layout_3col.html #}

web/app/main/templates/navbar_main.html
<nav id="navbar_main" class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">FlaskApp</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li -->
        <li><a href="{{ url_for('item.item_page', page='index') }}">Items</a></li>
        <li><a href="{{ url_for('user.user_page', page='index') }}">Users</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ url_for('main.main_page', page='admin') }}">Dashboard</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{ url_for('item.item_list') }}">Items</a></li>
            <li><a href="{{ url_for('user.user_list') }}">Users</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- end class="collapse navbar-collapse" -->

  </div><!-- end class="container-fluid" -->
</nav><!-- end id="navbar_main" -->

{# end web/app/main/templates/navbar_main.html #}